[workspace]
resolver = "2"
members = ["crates/common", "crates/engine", "crates/protocol", "crates/rmp-client", "crates/server"]

[workspace.package]
edition = "2021"
version = "0.1.2"

[workspace.dependencies]
bytes = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
bincode = "1"
thiserror = "1"
tracing = "0.1"
parking_lot = "0.12"
rand = "0.8"
ordered-float = "4"
tokio-util = { version = "0.7", features = ["codec"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "time", "sync"] }
futures-util = { version = "0.3", features = ["sink"] }
metrics = "0.24"
metrics-exporter-prometheus = { version = "0.18", default-features = false }
