[workspace]
resolver = "2"
members = ["crates/common", "crates/engine", "crates/protocol", "crates/server"]

[workspace.package]
edition = "2021"
version = "0.1.1"

[workspace.dependencies]
bytes = "1"
thiserror = "1"
tracing = "0.1"
parking_lot = "0.12"
tokio-util = { version = "0.7", features = ["codec"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "time"] }
futures-util = { version = "0.3", features = ["sink"] }
