[package]
name = "rocket-mem"
edition.workspace = true
version.workspace = true

[lib]
name = "rocket_mem"
path = "src/lib.rs"

[[bin]]
name = "rocket-mem"
path = "src/main.rs"

[dependencies]
engine = { path = "../engine" }
protocol = { path = "../protocol" }
common = { path = "../common" }
clap.workspace = true
bytes.workspace = true
figment.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures-util.workspace = true
metrics.workspace = true
metrics-exporter-prometheus.workspace = true

[dev-dependencies]
redis = { version = "0.27", features = ["tokio-comp"] }
rmp-client = { path = "../rmp-client" }
tempfile = "3"
figment = { workspace = true, features = ["test"] }
